plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'com.diffplug.spotless' version "${spotless_version}"
}

version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenCentral()
	maven {
		name = 'Fabric'
		url = 'https://maven.fabricmc.net/'
	}
	maven {
		name = "Fuzs Mod Resources"
		url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
	}
	maven {
		url = "https://maven.jamieswhiteshirt.com/libs-release"
		content {
			includeGroup "com.jamieswhiteshirt"
		}
	}
	maven {
		name = 'LDTTeam - Modding'
		url = 'https://ldtteam.jfrog.io/ldtteam/modding/'
	}
}

loom {
	accessWidenerPath = file('src/main/resources/chiselsandbits.accesswidener')

	runs {

		client {

			property 'mixin.debug', 'true'
			programArgs '--username', 'Dev'

			ideConfigGenerated = true
			runDir = 'run-client'
		}

		server {

			property 'mixin.debug', 'true'
			runDir = 'run-server'

			ideConfigGenerated = true
		}
	}
}


dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"


	modApi("fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${config_api_version}")
	include(modImplementation("com.jamieswhiteshirt:reach-entity-attributes:${reach_distance_api_version}"))
	include(modImplementation("com.communi-suggestu.saecularia-caudices:saecularia-caudices-fabric:${saeculariaCaudicesVersion}"))
}

processResources {
	inputs.property "version", project.version
	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

def faceRegionMergeCheck = tasks.register("faceRegionMergeCheck", JavaExec) {
	dependsOn testClasses
	classpath = sourceSets.test.runtimeClasspath
	mainClass = "mod.chiselsandbits.render.chiseledblock.FaceRegionMergeCheck"
}

tasks.named("check") {
	dependsOn faceRegionMergeCheck
}

javadoc{
	failOnError = false
}

java {
	withSourcesJar()
	withJavadocJar()
	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}" }
	}
}

spotless {
	java {
		palantirJavaFormat()
	}

	groovyGradle {
		greclipse()
	}
}
