# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Minecraft / loaders
minecraft_version=26.2
enabled_platforms=fabric,neoforge

# Fabric
fabric_loader_version=0.19.3
fabric_version=0.155.2+26.2

# NeoForge
neoforge_version=26.2.0.23-beta

# Architectury
architectury_version=21.0.7
architectury_plugin_version=3.5-SNAPSHOT

# Mod Properties
mod_version=1.3.16
maven_group=mod.chiselsandbits
archives_base_name=chiselsandbits

# Dependencies
fzzy_config_version=0.7.6+26.2

# Plugins
loom_version=1.17-SNAPSHOT
loom.ignoreDependencyLoomVersionValidation=true
spotless_version=8.8.0
